"""
Test custom Django Management Commands.
"""

from unittest.mock import patch

from psycopg2 import OperationalError as Psycopg2Error

from django.core.management import call_command
from django.db.utils import OperationalError
from django.test import SimpleTestCase


# mock behaviour
@patch("core.management.commands.wait_for_db.Command.check")
class CommandTests(SimpleTestCase):
    """Test commands."""

    def test_wait_for_db_ready(self, patched_check):
        "Test waiting for database if db ready"
        patched_check.return_value = True

        call_command("wait_for_db")

        patched_check.assert_called_once_with(databases=["default"])

    @patch("time.sleep")
    def test_wait_for_db_delay(self, patched_sleep, patched_check):
        """Testing waiting for database when getting Operational Eror"""
        # noqa   # Psycopg2Error=> First 2 time call mock method raise psycopg2Error, when db not started:: Operational Error => db started but not setup testing db or dev db, django raises operational error
        patched_check.side_effect = (
            [Psycopg2Error] * 2 + [OperationalError] * 3 + [True]
        )

        call_command("wait_for_db")

        self.assertEqual(patched_check.call_count, 6)
        # called with works for multiples times
        patched_check.assert_called_with(databases=["default"])
